server:
  port: 8080


spring:
  redis:
    host: redis
    port: 6379
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: GAME-LOBBY-SERVICE
          uri: lb://GAME-LOBBY-SERVICE
          predicates:
            - Path=/game-lobby/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/authenticate/**
          filters:
            - name: CircuitBreaker
              args:
                name: AUTH-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 100

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /v3/api-docs/authenticate
logging:
  level:
    org.springframework: DEBUG

battleship:
  jwt:
    secret: mySecretKey