server:
  port: 7779

spring:
  application:
    name: GAME-ENGINE-SERVICE
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  data:
    mongodb:
      username: test
      password: passwordvalue
      uri: mongodb://host:27017/d
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 5s
          multiplier: 2

springdoc:
  packagesToScan: com.battleship.gameengine


battleship:
  jwt:
    secret: mySecretKey
  rabbitmq:
    queue: lobby.message.queue