version: '3.8'

services:
  database:
    container_name: user-database
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    restart: always
    environment:
      #MYSQL_USER: root
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: testpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  spring-app:
    image: openjdk:11-jre-slim
    command: java -jar /app/auth-service-1.0-SNAPSHOT.jar
    volumes:
      - ./target/auth-service-1.0-SNAPSHOT.jar:/app/auth-service-1.0-SNAPSHOT.jar
    ports:
      - "7777:7777"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/userdb
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data: