version: '3.8'

services:
  database:
    container_name: gamelobby-database
    image: 'mysql:latest'
    ports:
      - "3307:3307"
    restart: always
    environment:
      #MYSQL_USER: root
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_TCP_PORT: 3307
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  backend:
    driver: bridge

volumes:
  db-data: