version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data: